telefonicaid/fiware-paas

doc/user_guide.rst
=> DOC Adding API and fixing some urls

rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/exception/ErrorCode.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/validation/TierResourceValidatorImpl.java
=> Wrong error message when tier is updated with invalid values for minimumNumberInstances, maximumNumberInstances and initialNumberInstances

core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/NetworkInstanceManagerImplTest.java
=> review comments

rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationFilter.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/RestAuthenticationEntryPoint.java, rest-api/src/main/resources/spring-security-config.xml, rest-api/src/test/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationFilterTest.java
@flopezag @hmunfru @jframos 
FIX bug https://jirapdi.tid.es/browse/CLAUDIA-4119 to avoid that a tenant accesses other tenants info
=> add header-vdc check + test

rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationFilter.java
@flopezag @hmunfru @jframos 
FIX order
=> change order to obtain desired error codes

core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackConfigUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackUtilImpl.java, core/src/main/resources/spring-model-config.xml, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackConfigUtilImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackUtilImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OperationUtilImplTest.java
=> close_wait socket bug

migrations/pom.xml
@hmunfru  
Change the Artifact ID of the migration pom in order that there is no conflict with SDC Manager / migrations
Locally
=> Change the Artifact Id of the migration

doc/user_guide.rst
=> Update github documentation including networks

core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/impl/TierDaoJpaImpl.java
=> fix bug: check null values

core/pom.xml, core/src/main/resources/ehcache.xml, migrations/pom.xml, model/pom.xml, pom.xml, rest-api/pom.xml, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationProvider.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/util/AdminTokenCache.java
=> admin token cache

core/src/main/resources/ehcache.xml, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationProvider.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationToken.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/util/TokenCache.java, rest-api/src/test/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationProviderTest.java, rest-api/src/test/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationTokenTest.java
=> cache token

core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/SecurityGroupDao.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/TierDao.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/impl/SecurityGroupDaoJpaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/impl/TierDaoJpaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/SecurityGroupManager.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/TierInstanceManager.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/TierManager.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/async/impl/EnvironmentInstanceAsyncManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/EnvironmentInstanceManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/SecurityGroupManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/TierInstanceManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/TierManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackSyncImpl.java, core/src/main/resources/spring-model-config.xml, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/SecurityGroupManagerImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/TierInstanceManagerImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/TierManagerImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackSyncImplTest.java, migrations/src/main/resources/db-changelog.sql, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/EnvironmentInstance.java, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/SecurityGroup.java, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/Tier.java, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/TierInstance.java, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/dto/TierInstanceDto.java, model/src/test/java/com/telefonica/euro_iaas/paasmanager/model/SecurityGroupTest.java, model/src/test/java/com/telefonica/euro_iaas/paasmanager/model/TierTest.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/exception/ErrorCode.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/resources/ProductReleaseResourceImpl.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/validation/TierResourceValidatorImpl.java
=> SecurityGroups creation and removal should be associated to TierInstance creation and removal

core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java, core/src/test/resources/userdata, src/assembly/jetty/resources/chef/install.sh, src/assembly/jetty/resources/userdata
@hmunfru @alberts-tid @flopezag @pratid 
FIX CLAUDIA-4689
- MOVE duplicated userdata file to test resources
- REFACTOR Chef installation procedure in userdata using only the "Chef" module of cloud-init
- ADD initial version of install.sh, copied from *https://www.opscode.com/chef/install.sh*
Fiware LAB with images: ubuntu12.04init, CentOS-6.3init, CentOS-6.5init, Ubuntu14.04init
=> [CLOUDINIT] FIX Chef installation procedure in userdata

test/acceptance/common_steps/paas_environment_provisioning.py, test/acceptance/integration/environments/api_restrictions/api_restrictions.feature, test/acceptance/integration/environments/api_restrictions/steps.py, test/acceptance/integration/instances/create_instance/create_instance.feature, test/acceptance/tools/terrain_steps.py
@hmunfru @jesuspg 
ADD Tier with different regions
FIX minor issues
DEL tags of fixed bugs
Locally
=> [QA] Tiers with different regions - TCs

core/src/main/resources/SystemConfiguration.properties
=> Removing quotes from config param user_data_path

core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/TierInstanceManagerImpl.java
=> Renaming securitygroups without service

pom.xml
=> fix, revert split line in rpm installation script section

src/assembly/jetty/bin/jetty.sh
=> force path to jetty.pid

rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/util/MyLoggingFilter.java, rest-api/src/main/webapp/WEB-INF/web.xml
=> Use custom LoggingFilter for jersey

src/assembly/jetty/etc/jetty-https.xml
=> add field acceptQueueSize in jetty-https 

core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/NetworkInstanceDao.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/impl/NetworkInstanceDaoJpaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/NetworkInstanceManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/SubNetworkInstanceManagerImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/dao/NetworkInstandSubNetInstDaoJpaImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/NetworkInstanceManagerImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/SubNetworkInstanceManagerImplTest.java
https://jirapdi.tid.es/browse/CLAUDIA-4455
tested locally
=> the net is deleted although there is a problem in openstack to delete

test/acceptance/integration/instances/create_instance/create_instance.feature, test/acceptance/integration/instances/create_instance/create_instance_attribute.feature, test/acceptance/integration/instances/create_instance/create_instance_open_ports.feature, test/acceptance/integration/instances/create_instance/steps.py, test/acceptance/integration/instances/create_instance/terrain.py, test/acceptance/tools/nova_request.py
@hmunfru @flopezag 
New test cases for CLAUDIA-4314: UDP Ports and Ranges in Sec. Groups.
Refactor in Terrain logic and product names.
Fix bug when product is created in SDC with attributes.
Locally.
=> [QA] CLAUDIA-4315 Range metadatas and UDP type support for Sec. Group rules

core/pom.xml, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/sdc/impl/ProductReleaseSdcDaoImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/installator/ProductInstallatorSdcImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/installator/sdc/util/SDCClient.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/installator/sdc/util/SDCUtil.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/installator/sdc/util/SDCUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/SDCClientConfigImpl.java, core/src/main/resources/spring-model-config.xml, core/src/test/java/com/telefonica/euro_iaas/paasmanager/installator/ProductInstallatorSdcImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/SDCUtilImplTest.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationProvider.java, rest-api/src/main/webapp/version.jsp
=> add new sdc client configuration using httpconnecitonmanager

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/main/resources/spring-model-config.xml
https://jira.tid.es/browse/CLAUDIA-4455
tested locally
=> Solve bug: loading all networks in DB from Openstack.

core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/SDCClientConfigImpl.java
(https://jirapdi.tid.es/browse/CLAUDIA-4855)
@jframos
=> fix: add hostname verifier

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/OpenstackFirewallingClientImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/keystone/impl/TokenDaoIdmImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/sdc/impl/ProductReleaseSdcDaoImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/TaskNotificatorImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/OpenStackRegionImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/dao/sdc/impl/ProductReleaseSdcDaoImplTest.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationProvider.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationToken.java
=> add response close operation for release the connection (hotfix/1.4.2)

core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/SecurityGroupManagerImplTest.java, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/Rule.java, model/src/test/java/com/telefonica/euro_iaas/paasmanager/model/SecurityGroupTest.java
https://jirapdi.tid.es/browse/CLAUDIA-4851
tested locally
=> Including rules tcp and upd where are the same

rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationProvider.java
=> fix; remove duplicated code

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/OpenstackNetworkClientImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/OpenStackNetworkImplTest.java, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/NetworkInstance.java
https://jira.tid.es/browse/CLAUDIA-4857
tested locally
=> If there are ports in a subnet, the interface cannot be deleted.

core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/sdc/ProductReleaseSdcDao.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/sdc/impl/ProductReleaseSdcDaoImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/dao/sdc/impl/ProductReleaseSdcDaoImplTest.java
=> remove method (not used)

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/OpenstackNetworkClientImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/OpenStackNetworkImplTest.java
https://jira.tid.es/browse/CLAUDIA-4857
tested locally
=> correct networkId to check ports

core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/AttributeDao.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/MetadataDao.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/ProductReleaseDao.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/impl/AttributeDaoJpaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/impl/MetadataDaoJpaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/impl/ProductReleaseDaoJpaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/ProductReleaseManagerImpl.java, core/src/main/resources/spring-dao-config.xml, core/src/main/resources/spring-model-config.xml, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/ProductReleaseManagerImplTest.java, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/ProductRelease.java, rest-api/src/test/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationProviderTest.java
=> FIX Syncrhonize updating new metada from sdc into paas database

core/pom.xml, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/SDCClientConfigImpl.java, migrations/pom.xml, model/pom.xml, pom.xml, rest-api/pom.xml
=> add default SSL context

doc/admin_guide.rst
=> Improving installation guide

core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/SDCClientConfigImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/impl/SDCClientConfigImplTest.java
=> fix bug: add default SSL context

core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtil.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackConfigUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackRegion.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/auth/OpenStackAuthenticationToken.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/OpenStackRegionImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackConfigUtilImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackUtilImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OperationUtilImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/auth/OpenStackAuthenticationTokenTest.java
=> refactor, change keystonePostRequest by getAdminToken with cache

doc/admin_guide.rst, scripts/bootstrap/centos.sh
=> Update installation guide to include script-installation and small modification on script

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java
https://jirapdi.tid.es/browse/CLAUDIA-4990
@jframos
=> Delete VM with admin creentials

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java
It obtains the puppet master hostname from the puppet master url obtained from keystone
=> It obtains the puppet master hostname from the puppet master url

core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/sdc/impl/ProductReleaseSdcDaoImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/installator/ProductInstallatorSdcImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/ProductReleaseManagerImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/dao/sdc/impl/ProductReleaseSdcDaoImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/installator/ProductInstallatorSdcImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/ProductReleaseImplTest.java
Bug in the configuration of attributes in the PaaS Manager
@jframos @jesuspg 
https://jira.tid.es/browse/CLAUDIA-5006
=> Error in configuration attributes

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java
@jframos @jesuspg 
https://jira.tid.es/browse/CLAUDIA-5007
=> Using shared network as the default network

python-paasmanagerclient/README.rst, python-paasmanagerclient/paasmanager_client/client.py, python-paasmanagerclient/paasmanager_client/environment_resource_client.py, python-paasmanagerclient/qa_utils/logger_utils.py, python-paasmanagerclient/qa_utils/rest_client_utils.py, python-paasmanagerclient/requirements.txt, python-paasmanagerclient/settings/logging.conf, python-paasmanagerclient/setup.py
@flopezag 
First version of Python-PaaSManagerClient for testing purposes. 
Implemented API operations:
- Create new environment.
- Delete environment.
Jekins is using these operations to test the PaaSManager service each 15 minutes.
Jenkins
=> [QA] Python-PaaSManagerClient

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/OpenstackNetworkClientImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/NetworkInstanceDao.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/dao/impl/NetworkInstanceDaoJpaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/NetworkInstanceManager.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/InfrastructureManagerClaudiaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/NetworkInstanceManagerImpl.java, core/src/main/resources/spring-model-config.xml, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/impl/InfrastructureManagerClaudiaImplTest.java
@jesuspg 
@jframos 
https://jira.tid.es/browse/CLAUDIA-5016
https://jira.tid.es/browse/CLAUDIA-5017
=> loading network with admin crendentials

core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackConfigUtilImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackConfigUtilImplTest.java
@jframos 
@jesuspg 
https://jirapdi.tid.es/browse/CLAUDIA-5028
=> Solvin bug when multiple external networks

core/src/main/resources/spring-task-config.xml
***** REVIEWERS *****
@jesuspg
=> FIX asyncronous task max core to 20

test/acceptance/integration/instances/create_instance/create_instance_networks.feature, test/acceptance/integration/instances/create_instance/steps.py, test/acceptance/settings/dev-properties.json, test/acceptance/tools/constants.py, test/acceptance/tools/nova_request.py
@hmunfru @flopezag 
Some test cases using networks with E2E validations.
Locally.
=> [QA]  New feature to test the Shared-Net behaviour

rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationFilter.java, rest-api/src/test/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationFilterTest.java
=> fix: accept parameter in header not is mandatory

core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/async/impl/EnvironmentInstanceAsyncManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/EnvironmentManagerImpl.java
******* REVIEWERS ******
@jesuspg
=> Improve error dails in logs when a Exception is thrown in Environment and EnvironmentInstance actions

test/acceptance/integration/instances/create_instance/terrain.py
@jesuspg 
Due to unresolved bug of Lettuce: https://github.com/gabrielfalcao/lettuce/pull/437, it is need to do a  refactor in terrain file.
Locally.
=> [QA] Refactor in terrain.py file (hooks order for outlines)

rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/auth/OpenStackAuthenticationFilter.java
=> add '*/*' like valid value to accept header parameter

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClient.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/InfrastructureManagerClaudiaImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackUtil.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/SystemPropertiesProvider.java, core/src/main/resources/SystemConfiguration.properties, core/src/main/resources/SystemConfigurationTest.properties, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/impl/InfrastructureManagerClaudiaImplTest.java, rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/resources/EnvironmentInstanceResourceImpl.java
@hmunfru @jframos 
solution: bug minor 4338, and removed a 'while true' in waiting for delete
Locally.
=> change ERROR traces; while true

core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/NetworkManager.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/NetworkManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/SubNetworkManagerImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/manager/impl/TierManagerImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/dao/NetworkandSubNetDaoJpaImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/manager/NetworkManagerImplTest.java, model/src/main/java/com/telefonica/euro_iaas/paasmanager/model/Network.java
@hmunfru @jframos 
solution: bugs 5030 / 5031
Locally.
=> refactor creation of networks/subnetworks

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java, core/src/test/resources/userdata, src/assembly/jetty/resources/userdata
Reverts telefonicaid/fiware-paas#235
=> Revert "Story/claudia 5159"

test/acceptance/integration/e2e/test_chef_puppet_on_base_images/steps.py, test/acceptance/integration/e2e/test_chef_puppet_on_base_images/terrain.py, test/acceptance/integration/e2e/test_chef_puppet_on_base_images/test_chef_puppet_on_base_images.feature, test/acceptance/settings/dev-properties.json, test/acceptance/tools/constants.py, test/acceptance/tools/fabric_utils.py, test/acceptance/tools/nova_request.py
@hmunfru 
E2E tests to check the installation of producs in VMs deployed using each new base image (Chef and Puppet)
Locally.
=> Automated tests to check product installation in new images

scripts/recipes_checking/recipes_checking.py
=> FIX: Adapting call to changes in python-paasmanager client task resource

src/assembly/jetty/etc/jetty-ssl.xml
=> add items in order to disable cipher suites

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java
=> Removing disAllocateFloatingIP after delete VM

doc/user_guide.rst
=> Update PaasManager documentation

doc/user_guide.rst
=> Indentation corrections in users_guide

doc/admin_guide.rst
=> Adapting the doc file to ReadTheDocs

index.rst
=> Including PaaS Manager description in index

conf.py
=> Changing project name in readthedocs

scripts/recipes_checking/recipes_checking.py
=> Replacing time units in a log text

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackUtilImpl.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackUtilImplTest.java
@jesuspg @jframos 
Still testing
=> changes for including JSON instead of XML

scripts/recipes_checking/recipes_checking.py
=> Including images-products whose image id is not the first in the image metadata list and some comments

scripts/recipes_checking/recipes_checking.py
=> Adding the products without metadatas to the image_productrelease list

scripts/recipes_checking/recipes_checking.py
=> Identation corrected

rest-api/src/main/java/com/telefonica/euro_iaas/paasmanager/rest/validation/ProductValidatorImpl.java
=> fix: add warning trace, to follow fails with invalid attributes

core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtil.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackRegion.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/SupportServerUtils.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/SupportServerUtilsImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/OpenStackRegionImpl.java, core/src/main/resources/spring-model-config.xml, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/SupportUtilImplTest.java
=> Obtaining support information for the Support Key server

core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/OpenStackRegionImpl.java, src/assembly/jetty/resources/userdata
=> Modifying user data for support key

README.rst, doc/admin_guide.rst, doc/user_guide.rst
@hmunfru 
- Change rst files to generate properly the pdf file from the ReadTheDocs
- Do not delete the branch before checking the pdf generated in ReadTheDocs
Visualisation correctly in github
=> Change doc files in order to generate correctly the pdf from ReadTheDocs

README.rst, doc/admin_guide.rst, doc/user_guide.rst
@hmunfru 
Detected some errors again in the pdf generation
in github
=> Resolve pdf error generation again.

README.rst, doc/admin_guide.rst, doc/user_guide.rst
=> Resolve errors in the pdf generation from ReadTheDocs

.travis.yml, README.rst, apiary.apib, core/pom.xml, core/src/main/java/com/telefonica/euro_iaas/paasmanager/claudia/impl/ClaudiaClientOpenStackImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtil.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenStackRegion.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/SupportServerUtils.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/SupportServerUtilsImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/impl/OpenStackRegionImpl.java, core/src/main/resources/spring-model-config.xml, core/src/test/java/com/telefonica/euro_iaas/paasmanager/claudia/ClaudiaClientOpenStackImplTest.java, core/src/test/java/com/telefonica/euro_iaas/paasmanager/util/SupportUtilImplTest.java, doc/admin_guide.rst, doc/user_guide.rst, migrations/pom.xml, model/pom.xml, pom.xml, rest-api/pom.xml, src/assembly/jetty/resources/userdata
=> Change the aiakos endpoint

core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/OpenOperationUtilImpl.java, core/src/main/java/com/telefonica/euro_iaas/paasmanager/util/SupportServerUtilsImpl.java
=> Update the way to obtain the support server endpoint
